Repository faebryk/faebryk, pull requests merged in 2022-10, with the labels that each got.

#119 Packaging: Fix missing dependencies
  examples/iterative_design_nand.py
  examples/resistors_and_nand.py
  pyproject.toml
  setup.cfg
Labels: 🛠 goal: bug fix, 🟨 priority: medium, 🤖 area: ci/cd

#143 Bugfix: add "fields" to netlist importer
  src/faebryk/libs/kicad/parser.py
Labels: 🛠 goal: bug fix

#144 Bugfix: Readme: Fix example instructions
  README.md
Labels: 🛠 goal: bug fix, 📄 area: documentation, 🟨 priority: medium

#145 Bugfix: Tools: Fix aliased pins in converter
  src/faebryk/exporters/netlist/graph.py
  src/faebryk/library/core.py
  src/faebryk/libs/kicad/parser.py
  src/faebryk/libs/util.py
  tools/symbol_converter/main.py
Labels: 🛠 goal: bug fix, ⛏️ area: tools
