Repository faebryk/faebryk, pull requests merged in 2022-04, with the labels that each got.

#78 Core: Add backref in traits to their object
  faebryk/library/core.py
  faebryk/library/library/components.py
  faebryk/library/traits/component.py
  samples/iterative_design_nand.py
  samples/resistors_and_nand.py
  test/exporters/netlist/kicad/test_netlist_kicad.py
Labels: ✨ goal: improvement, 🟧 priority: high, 💻 area: core

#82 Meta: Bugfix: Fix git blame ignore revs for black
  .git-blame-ignore-revs
Labels: 🛠 goal: bug fix, 🟨 priority: medium, ⛏️ area: tools

#85 PR template: Remove pr type
  .github/pull_request_template.md
Labels: ✨ goal: improvement, 🟩 priority: low, 🤖 area: ci/cd

#84 Feature/add code formatting request
  .github/pull_request_template.md
  docs/CONTRIBUTING.md
Labels: ✨ goal: improvement, 🟨 priority: medium, 🤖 area: ci/cd

#87 Change: Print to logging
  faebryk/exporters/netlist/kicad/netlist_kicad.py
  samples/iterative_design_nand.py
  samples/resistors_and_nand.py
  scripts/clean_issues.py
  test/exporters/netlist/kicad/test_netlist_kicad.py
  test/exporters/netlist/kicad/test_sexp.py
Labels: ✨ goal: improvement, 🟨 priority: medium, 💻 area: core, 🗂 area: library, ⛏️ area: tools, 🧐 area: samples
