Repository faebryk/faebryk, pull requests merged in 2022-03, with the labels that each got.

#47 Meta: Contributing guide & Code of conduct
  docs/CODE_OF_CONDUCT.md
  docs/CODING_GUIDELINES.md
  docs/CONTRIBUTING.md
Labels: 📄 area: documentation, ⭐ goal: addition, 🟩 priority: low

#51 Template fixes and removals
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
Labels: 🛠 goal: bug fix, 🟩 priority: low, 🤖 area: ci/cd

#62 Meta: Ignore _local folder in gitignore
  .gitignore
Labels: ⭐ goal: addition, 🟩 priority: low, ⛏️ area: tools

#63 Scripts: clean issues script
  scripts/clean_issues.py
Labels: ⭐ goal: addition, 🟩 priority: low, ⛏️ area: tools

#65 Sample: Add explanation to current examples
  samples/iterative_design_nand.py
  samples/resistors_and_nand.py
Labels: ⭐ goal: addition, 🟧 priority: high, 🧐 area: samples

#68 Meta: Discord, PyPi, commit activity labels
  README.md
Labels: 📄 area: documentation, ✨ goal: improvement, 🟩 priority: low

#69 Meta: Add pip instructions to README
  README.md
Labels: 📄 area: documentation, ⭐ goal: addition, 🟧 priority: high
